#!/usr/bin/env ruby

require "rubygems"
require "bundler/setup"

require "logger"
require 'gosu'
require "chingu"

require 'pry'

ROOT_PATH = File.dirname(File.expand_path(__FILE__))
require_all "#{ROOT_PATH}/src"

ArkanoidGame.new.show